### ISSUE TITLE
UserWarning: Could not deserialize object lr_schedule. Consider using `custom_objects` argument to replace this object.

### ISSUE THREAD

**Issue by lb20150514** [sunnyswag/StockRL#2]
/home/xxx/.local/lib/python3.8/site-packages/stable_baselines3/common/save_util.py:166: UserWarning: Could not deserialize object lr_schedule. Consider using `custom_objects` argument to replace this object.
  warnings.warn(
/home/xxx/.local/lib/python3.8/site-packages/stable_baselines3/common/save_util.py:166: UserWarning: Could not deserialize object clip_range. Consider using `custom_objects` argument to replace this object.
  warnings.warn(
Traceback (most recent call last):
  File "./trader.py", line 129, in <module>
    start_trade()
  File "./trader.py", line 126, in start_trade
    Trader(model_name = options.model).trade()
  File "./trader.py", line 45, in trade
    model = self.get_model(agent)
  File "./trader.py", line 83, in get_model
    model.load(model_dir)
  File "/home/xxx/.local/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 687, in load
    model._setup_model()
  File "/home/xxx/.local/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py", line 158, in _setup_model
    self.clip_range = get_schedule_fn(self.clip_range)
  File "/home/xxx/.local/lib/python3.8/site-packages/stable_baselines3/common/utils.py", line 88, in get_schedule_fn
    assert callable(value_schedule)
AssertionError

请问这个bug要怎么解决

**Comment by sunnyswag** [comment]
是不是 model_dir 为空呢，可以去 [release](https://github.com/sunnyswag/RL_in_Stock/releases/tag/1.0) 上下个 model 放本地跑一下

**Comment by lb20150514** [comment]
之前放了model了...其他机器上centos系统能跑，但本机ubuntu跑不出来，环境原因么？

**Comment by sunnyswag** [comment]
应该是的，可以使用 [matpol](https://www.matpool.com/host-market?type=GPU) 的 finrl 镜像试试
